import { ReportData } from "@/types/report";

export const MOCK_REPORT_DATA: ReportData = {
  meta: {
    period: "Março 2025",
    comparisonPeriod: "Fevereiro 2025",
    generatedAt: new Date().toISOString(),
    clientName: "Empresa Demonstração",
    dataSource: { reportei: true, crm: true },
  },
  kpis: {
    totalInvestment: {
      value: 45230,
      formatted: "R$ 45.230",
      trend: 8.5,
      trendDirection: "up",
    },
    totalLeads: {
      value: 1847,
      formatted: "1.847",
      trend: 12.3,
      trendDirection: "up",
    },
    costPerLead: {
      value: 24.49,
      formatted: "R$ 24,49",
      trend: -3.5,
      trendDirection: "down",
    },
    totalSales: {
      value: 67,
      formatted: "67",
      trend: 15.2,
      trendDirection: "up",
    },
    revenue: {
      value: 387540,
      formatted: "R$ 387.540",
      trend: 18.7,
      trendDirection: "up",
    },
    roas: {
      value: 8.57,
      formatted: "8,57x",
      trend: 6.8,
      trendDirection: "up",
    },
    cac: {
      value: 675,
      formatted: "R$ 675",
      trend: -2.8,
      trendDirection: "down",
    },
    sessions: {
      value: 98432,
      formatted: "98.432",
      trend: 9.1,
      trendDirection: "up",
    },
    impressions: {
      value: 2847650,
      formatted: "2,85M",
      trend: 5.4,
      trendDirection: "up",
    },
    ctr: {
      value: 4.48,
      formatted: "4,48%",
      trend: -0.3,
      trendDirection: "down",
    },
    mqls: {
      value: 742,
      formatted: "742",
      trend: 11.2,
      trendDirection: "up",
    },
    conversionRate: {
      value: 3.63,
      formatted: "3,63%",
      trend: 2.1,
      trendDirection: "up",
    },
  },
  charts: {
    timeSeries: [
      { date: "01/03", leads: 58, revenue: 12000, investment: 1450, sessions: 3100 },
      { date: "03/03", leads: 62, revenue: 13500, investment: 1520, sessions: 3280 },
      { date: "05/03", leads: 71, revenue: 14200, investment: 1490, sessions: 3450 },
      { date: "07/03", leads: 55, revenue: 10800, investment: 1380, sessions: 2980 },
      { date: "09/03", leads: 79, revenue: 15600, investment: 1680, sessions: 3790 },
      { date: "11/03", leads: 83, revenue: 16900, investment: 1720, sessions: 4010 },
      { date: "13/03", leads: 68, revenue: 13100, investment: 1460, sessions: 3290 },
      { date: "15/03", leads: 91, revenue: 18200, investment: 1850, sessions: 4320 },
      { date: "17/03", leads: 87, revenue: 17400, investment: 1790, sessions: 4180 },
      { date: "19/03", leads: 74, revenue: 14800, investment: 1560, sessions: 3570 },
      { date: "21/03", leads: 96, revenue: 19100, investment: 1920, sessions: 4580 },
      { date: "23/03", leads: 102, revenue: 20400, investment: 2010, sessions: 4820 },
      { date: "25/03", leads: 88, revenue: 17600, investment: 1830, sessions: 4230 },
      { date: "27/03", leads: 112, revenue: 22400, investment: 2180, sessions: 5320 },
      { date: "29/03", leads: 98, revenue: 19600, investment: 1980, sessions: 4680 },
      { date: "31/03", leads: 123, revenue: 24600, investment: 2400, sessions: 5820 },
    ],
    channelComparison: [
      {
        name: "Google Ads",
        color: "#3b82f6",
        investment: 18500,
        impressions: 980000,
        clicks: 52400,
        ctr: 5.35,
        cpc: 3.53,
        cpm: 18.88,
        sessions: 41200,
        leads: 823,
        cpl: 22.48,
        mqls: 342,
        sqls: 138,
        sales: 32,
        revenue: 170240,
        roas: 9.2,
      },
      {
        name: "Meta Ads",
        color: "#8b5cf6",
        investment: 15200,
        impressions: 1320000,
        clicks: 48600,
        ctr: 3.68,
        cpc: 3.13,
        cpm: 11.52,
        sessions: 38400,
        leads: 654,
        cpl: 23.24,
        mqls: 261,
        sqls: 105,
        sales: 24,
        revenue: 118560,
        roas: 7.8,
      },
      {
        name: "LinkedIn Ads",
        color: "#06b6d4",
        investment: 8900,
        impressions: 320000,
        clicks: 7840,
        ctr: 2.45,
        cpc: 11.35,
        cpm: 27.81,
        sessions: 7100,
        leads: 187,
        cpl: 47.59,
        mqls: 102,
        sqls: 41,
        sales: 8,
        revenue: 54320,
        roas: 6.1,
      },
      {
        name: "TikTok Ads",
        color: "#10b981",
        investment: 2630,
        impressions: 227650,
        clicks: 18645,
        ctr: 8.19,
        cpc: 1.41,
        cpm: 11.56,
        sessions: 11732,
        leads: 183,
        cpl: 14.37,
        mqls: 37,
        sqls: 14,
        sales: 3,
        revenue: 12420,
        roas: 4.7,
      },
    ],
    funnelStages: [
      {
        label: "Impressões",
        sublabel: "Pessoas que viram seus anúncios",
        value: 2847650,
        formatted: "2.847.650",
        conversionRate: 100,
        color: "#3b82f6",
        icon: "eye",
      },
      {
        label: "Cliques",
        sublabel: "Pessoas que clicaram nos anúncios",
        value: 127485,
        formatted: "127.485",
        conversionRate: 4.48,
        color: "#60a5fa",
        icon: "cursor",
      },
      {
        label: "Sessões",
        sublabel: "Visitas ao site",
        value: 98432,
        formatted: "98.432",
        conversionRate: 77.2,
        color: "#8b5cf6",
        icon: "globe",
      },
      {
        label: "Leads",
        sublabel: "Contatos gerados",
        value: 1847,
        formatted: "1.847",
        conversionRate: 1.88,
        color: "#a78bfa",
        icon: "users",
      },
      {
        label: "MQLs",
        sublabel: "Leads qualificados pelo marketing",
        value: 742,
        formatted: "742",
        conversionRate: 40.2,
        color: "#06b6d4",
        icon: "star",
      },
      {
        label: "SQLs",
        sublabel: "Leads qualificados pelo comercial",
        value: 298,
        formatted: "298",
        conversionRate: 40.2,
        color: "#22d3ee",
        icon: "check-circle",
      },
      {
        label: "Oportunidades",
        sublabel: "Propostas em andamento",
        value: 189,
        formatted: "189",
        conversionRate: 63.4,
        color: "#f59e0b",
        icon: "briefcase",
      },
      {
        label: "Vendas",
        sublabel: "Negócios fechados",
        value: 67,
        formatted: "67",
        conversionRate: 35.4,
        color: "#10b981",
        icon: "trophy",
      },
    ],
    campaigns: [
      {
        id: "1",
        name: "Google – Pesquisa Branded",
        channel: "Google Ads",
        investment: 5200,
        leads: 312,
        cpl: 16.67,
        sales: 14,
        roas: 12.4,
        status: "scaling",
      },
      {
        id: "2",
        name: "Meta – Conversão – Público Frio",
        channel: "Meta Ads",
        investment: 6800,
        leads: 298,
        cpl: 22.82,
        sales: 11,
        roas: 8.1,
        status: "ok",
      },
      {
        id: "3",
        name: "Google – Performance Max",
        channel: "Google Ads",
        investment: 7400,
        leads: 276,
        cpl: 26.81,
        sales: 11,
        roas: 8.8,
        status: "ok",
      },
      {
        id: "4",
        name: "Meta – Remarketing 30 dias",
        channel: "Meta Ads",
        investment: 4200,
        leads: 198,
        cpl: 21.21,
        sales: 9,
        roas: 9.4,
        status: "scaling",
      },
      {
        id: "5",
        name: "LinkedIn – Decision Makers",
        channel: "LinkedIn Ads",
        investment: 5100,
        leads: 89,
        cpl: 57.30,
        sales: 4,
        roas: 5.8,
        status: "monitor",
      },
      {
        id: "6",
        name: "TikTok – Top of Funnel",
        channel: "TikTok Ads",
        investment: 2630,
        leads: 183,
        cpl: 14.37,
        sales: 3,
        roas: 4.7,
        status: "monitor",
      },
      {
        id: "7",
        name: "LinkedIn – Brand Awareness",
        channel: "LinkedIn Ads",
        investment: 3800,
        leads: 98,
        cpl: 38.78,
        sales: 4,
        roas: 6.6,
        status: "monitor",
      },
    ],
  },
  insights: [
    {
      id: "ins-1",
      type: "positive",
      title: "ROAS 8,57x acima da meta",
      executiveText:
        "O retorno sobre investimento em mídia atingiu 8,57x no período, superando a meta de 6x em 43%. A combinação de branded search com remarketing multicanal foi determinante para o resultado. Receita cresceu 18,7% em relação ao mês anterior.",
      laymanText:
        "Para cada R$1 investido em anúncios, o negócio gerou R$8,57 de receita. Isso é um resultado excelente — significa que a publicidade está gerando muito mais do que está custando. A meta era retornar 6x e chegamos a quase 9x.",
      metric: "ROAS",
      metricValue: "8,57x",
      metricTrend: 6.8,
    },
    {
      id: "ins-2",
      type: "opportunity",
      title: "Google Ads com potencial de escala imediata",
      executiveText:
        "Google Ads apresenta o melhor CPL entre canais pagos (R$22,48) com o maior volume de leads (823) e ROAS de 9,2x. O orçamento atual pode ser escalado em 20-30% sem perda de eficiência estimada. Prioridade: campanhas de pesquisa branded e Performance Max.",
      laymanText:
        "O Google Ads está sendo o canal mais eficiente de todos — tanto no volume de leads quanto no retorno financeiro. Como ele está funcionando muito bem, colocar mais dinheiro aqui provavelmente vai gerar mais resultados proporcionalmente.",
      metric: "CPL Google",
      metricValue: "R$ 22,48",
      metricTrend: -4.2,
    },
    {
      id: "ins-3",
      type: "alert",
      title: "Gargalo crítico: SQL → Oportunidade (63,4%)",
      executiveText:
        "Apenas 63,4% dos SQLs estão sendo convertidos em Oportunidades, abaixo do benchmark de 75% do setor. Isso representa 54 oportunidades perdidas no mês — equivalente a aproximadamente R$54.000 em receita potencial não realizada. Investigar processo de abordagem comercial.",
      laymanText:
        "Existe um problema no processo de vendas: de cada 10 pessoas que o time comercial considerou prontas para comprar, apenas 6 viraram uma proposta real. Isso significa que vendas está perdendo oportunidades boas. Vale investigar o que acontece nessa etapa.",
      metric: "SQL → Oport.",
      metricValue: "63,4%",
      metricTrend: -8.2,
    },
    {
      id: "ins-4",
      type: "attention",
      title: "LinkedIn: CPL alto pode ser justificado pela qualidade",
      executiveText:
        "O CPL do LinkedIn (R$47,59) é 2,1x acima da média dos demais canais. Porém, os 8 negócios fechados via LinkedIn têm ticket médio estimado 40% superior. Recomenda-se análise de LTV por canal antes de reduzir orçamento. Se a qualidade se confirmar, o canal está subinvestido.",
      laymanText:
        "Trazer um lead pelo LinkedIn custa bem mais do que nos outros canais. Mas há um sinal de que esses leads compram mais e em valores maiores. Antes de cortar o investimento, vale investigar se os clientes que vieram do LinkedIn são mais lucrativos no longo prazo.",
      metric: "CPL LinkedIn",
      metricValue: "R$ 47,59",
      metricTrend: 3.1,
    },
  ],
};
